
services:
    nextjs:
      build:
      container_name: fullstackapp
      ports:
      - "3000:3000"
      env_file: #lee el archivo env
      - .env
      depends_on:
      - postgres

    postgres:
      image: postgres:16 
      container_name: fullstackappDB
      restart: always
      environment: # Usuario/DB
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: fullstackdb