
services:
    nextjs:
      build:
      container_name: fullstackapp
      ports:
      - "3000:3000"
      env_file: #lee el archivo env
      - .env
      depends_on:
      - postgres

    postgres: