
services:
    nextjs:
      build:
      container_name: fullstackapp
      ports:
      - "3000:3000"
      env_file: #lee el archivo env
      - .env
      depends_on:
      - postgres

    postgres:
      image: postgres:16 
      container_name: fullstackappDB
      restart: always
      environment: # User/DB
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: fullstackdb
      ports: #external acccess
      - "5433:5432"
      volumes:
      - postgres_data:/var/lib/postgresql/data